//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace CodeCube.Mvc.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resource {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Borlo.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one minute ago.
        /// </summary>
        public static string AMinuteAgo {
            get {
                return ResourceManager.GetString("AMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in one hour.
        /// </summary>
        public static string InAnHour {
            get {
                return ResourceManager.GetString("InAnHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in a minute.
        /// </summary>
        public static string InAnMinute {
            get {
                return ResourceManager.GetString("InAnMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in one week.
        /// </summary>
        public static string InAWeek {
            get {
                return ResourceManager.GetString("InAWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} days.
        /// </summary>
        public static string InXDays {
            get {
                return ResourceManager.GetString("InXDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} hours.
        /// </summary>
        public static string InXHours {
            get {
                return ResourceManager.GetString("InXHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} minutes.
        /// </summary>
        public static string InXMinutes {
            get {
                return ResourceManager.GetString("InXMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} months.
        /// </summary>
        public static string InXMonths {
            get {
                return ResourceManager.GetString("InXMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0} weeks.
        /// </summary>
        public static string InXWeeks {
            get {
                return ResourceManager.GetString("InXWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a choice.
        /// </summary>
        public static string MakeAChoice {
            get {
                return ResourceManager.GetString("MakeAChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an hour ago.
        /// </summary>
        public static string OneHourAgo {
            get {
                return ResourceManager.GetString("OneHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one week ago.
        /// </summary>
        public static string OneWeekAgo {
            get {
                return ResourceManager.GetString("OneWeekAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option.
        /// </summary>
        public static string SelectAnItem {
            get {
                return ResourceManager.GetString("SelectAnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string xDaysAgo {
            get {
                return ResourceManager.GetString("xDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string xHoursAgo {
            get {
                return ResourceManager.GetString("xHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minuten geleden.
        /// </summary>
        public static string xMinutesAgo {
            get {
                return ResourceManager.GetString("xMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        public static string xMonthsAgo {
            get {
                return ResourceManager.GetString("xMonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weken geleden.
        /// </summary>
        public static string xWeeksAgo {
            get {
                return ResourceManager.GetString("xWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        public static string xYearsAgo {
            get {
                return ResourceManager.GetString("xYearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
